plugins:
  audioplayers: ["IOT-Headed-6.0", "tv-7.0"]
  battery_plus: ["IOT-Headed-6.0"]
  connectivity_plus: ["IOT-Headed-6.0", "tv-7.0"]
  device_info_plus: ["IOT-Headed-6.0", "tv-7.0"]
  flutter_app_badger: ["IOT-Headed-6.0"]
  flutter_secure_storage: ["IOT-Headed-6.0", "tv-7.0"]
  flutter_tts: ["IOT-Headed-6.0", "tv-7.0"]
  integration_test: ["IOT-Headed-6.0", "tv-7.0"]
  messageport: ["IOT-Headed-6.0", "tv-7.0"]
  package_info_plus: ["IOT-Headed-6.0", "tv-7.0"]
  path_provider: ["IOT-Headed-6.0", "tv-7.0"]
  permission_handler: ["IOT-Headed-6.0"]
  sensors_plus: ["IOT-Headed-6.0"]
  shared_preferences: ["IOT-Headed-6.0", "tv-7.0"]
  sqflite: ["IOT-Headed-6.0", "tv-7.0"]
  tizen_app_manager: ["IOT-Headed-6.0", "tv-7.0"]
  tizen_audio_manager: ["IOT-Headed-6.0", "tv-7.0"]
  tizen_bundle: ["IOT-Headed-6.0", "tv-7.0"]
  tizen_package_manager: ["IOT-Headed-6.0", "tv-7.0"]
  tizen_rpc_port: ["tv-7.0"]
  url_launcher: ["IOT-Headed-6.0", "tv-7.0"]
  wakelock: ["IOT-Headed-6.0"]

  # No tests.
  google_sign_in: []
  image_picker: []
  firebase_core: []
  tizen_log: []
  tizen_notification: []
  wearable_rotary: []

  # Functionality not available on emulator.
  camera: []
  flutter_webrtc: []
  geolocator: []
  in_app_purchase: []
  network_info_plus: []
  video_player_avplay: []
  video_player_videohole: []

  # Only testable with the drive command: https://github.com/flutter-tizen/plugins/issues/272
  tizen_app_control: []

  # Test frequently breaks due to memory issue: https://github.com/flutter-tizen/plugins/issues/135
  video_player: []

  # Temporarily disabled due to test_api error. Testable with the drive command.
  # https://github.com/flutter-tizen/plugins/pull/397#issuecomment-1139299838
  webview_flutter: []
  webview_flutter_lwe: []

  # Temporarily disabled due to the test runner not responding issue.
  google_maps_flutter: []
