name: tizen_bundle
description: Tizen data bundle APIs.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/tizen_bundle
version: 0.1.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  tizen_interop: ^0.3.0
