name: firebase_core_tizen_example
description: An example application demonstrating calls to Firebase Core.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  firebase_core: ^2.4.0
  firebase_core_tizen:
    path: ../
  flutter:
    sdk: flutter
