name: image_picker_tizen_example
description: Demonstrates how to use the image_picker_tizen plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  image_picker_tizen:
    path: ../
  mime: ^1.0.4
  video_player: ^2.4.2
  video_player_tizen: ^2.4.7

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/

flutter:
  uses-material-design: true
