name: network_info_plus_example
description: Demonstrates how to use the network_info_plus_tizen plugin.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^4.1.0
  network_info_plus_tizen:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen:
    path: ../../integration_test/
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
