name: video_player_tizen
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Tizen.
version: 1.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VideoPlayerTizenPlugin
        fileName: video_player_tizen_plugin.h

dependencies:
  video_player_platform_interface:
    git:
      url: git@github.sec.samsung.net:xiaowei-guan/video_player_platform_interface.git
      ref: 17229244247466adb4bd93298b4f1aaafc9960b9
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0<3.0.0"
  flutter: ">=2.0.0"
