name: tizen_log
description: A Flutter plugin which provides the ability to use Tizen dlog logging service.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/tizen_log
version: 0.1.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  ffi: ">=1.1.2 <3.0.0"
