name: battery_plus_tizen
description: Tizen implementation of the battery_plus plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/battery_plus
version: 1.1.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: BatteryPlusTizenPlugin
        fileName: battery_plus_tizen_plugin.h

dependencies:
  battery_plus_platform_interface: ^1.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
